
# Pour tout push dans le repo
# - déclencher le build d'une nouvelle image docker en utilisant le Dockerfile
# - et faire un push vers dockerHub

name: build and push image
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: tree
    - uses: docker/build-push-action@v2
    with:
      push: true
