
# Pour tout push dans le repo
# - déclencher le build d'une nouvelle image docker en utilisant le Dockerfile
# - et faire un push vers dockerHub

name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag getting-started

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push getting-started
